D2: false
adam: true
batch_size: 8
bg: true
channel: 6
class_num: 1041
cluster: xyzrgb
conv: EdgeConv
dataset_path: 2DMSMT
drop_connect_rate: 0.0
droprate: 0.5
erase: 0.0
feature_dims:
- 48
- 96
- 192
- 384
flip: true
gpu_ids:
- 0
id_skip: false
init_points: 768
jitter: false
k: 20
labelsmooth: false
light: false
load_model_path: ''
lrRate: 0.00035
name: ALL_MSMT_SDense_b8_lr3.5_flip_slim0.5_warm5_scale_e0_d5+bg_adam_init768_clusterXYZRGB
no_xyz: false
norm: false
npart: 1
num_epochs: 150
num_workers: 2
res_scale: 1.0
resume: false
rotate: false
scale: true
slim: 0.5
step: false
train_all: true
use_DGCNN: false
use_MSG: false
use_SSG: false
use_dense: true
use_dense2: false
warm_epoch: 5
